import{Jugadores}from './Jugadores';
export class Equipos{
    id=0;
    nombre="";
    ciudad="";
    jugadores:Jugadores[];
}
export const ListaEquipos = [{
    id:1,
    nombre:"Azul",
    ciudad:"Este",
    jugadores:[{
        id:1,
        nombre:"Jugador",
        apellido:"Azul"
    },
    {
        id:2,
        nombre:"Jugador",
        apellido:"Azul"
    },
    {
        id:3,
        nombre:"Jugador",
        apellido:"Azul"
    },
    {
        id:4,
        nombre:"Jugador",
        apellido:"Azul"
    },
    {
        id:5,
        nombre:"Jugador",
        apellido:"Azul"
    }
    ]
},
{
    id:1,
    nombre:"Rojo",
    ciudad:"Este",
    jugadores:[{
        id:6,
        nombre:"Jugador",
        apellido:"Rojo"
    },
    {
        id:7,
        nombre:"Jugador",
        apellido:"Rojo"
    },
    {
        id:8,
        nombre:"Jugador",
        apellido:"Rojo"
    },
    {
        id:9,
        nombre:"Jugador",
        apellido:"Rojo"
    },
    {
        id:10,
        nombre:"Jugador",
        apellido:"Rojo"
    }
    ]
},
{
    id:3,
    nombre:"Verde",
    ciudad:"Centro",
    jugadores:[{
        id:11,
        nombre:"Jugador",
        apellido:"Verde"
    },
    {
        id:12,
        nombre:"Jugador",
        apellido:"Verde"
    },
    {
        id:13,
        nombre:"Jugador",
        apellido:"Verde"
    },
    {
        id:14,
        nombre:"Jugador",
        apellido:"Verde"
    },
    {
        id:15,
        nombre:"Jugador",
        apellido:"Verde"
    }
    ]
}]